# Build stage
FROM node:22-bookworm AS build
WORKDIR /app
COPY web_wallet/package.json web_wallet/yarn.lock ./
RUN --mount=type=cache,target=/root/.yarn-cache yarn install
COPY web_wallet/ ./web_wallet/
WORKDIR /app/web_wallet
RUN yarn build-no-check  # Adjusted to use yarn

# Production stage
FROM nginx:latest
COPY --from=build /app/web_wallet/dist /usr/share/nginx/html
