{
 "title": "Nuklai Devnet",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "CHAIN_ID", "query": "CHAIN_ID_VAL" }
  ]
 },
 "panels": [
  { "title": "Transaction Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transactions Finalized (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(avalanche_${CHAIN_ID}_vm_hypersdk_vm_txs_included[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions Finalized (Cummulative)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "avalanche_${CHAIN_ID}_vm_hypersdk_vm_txs_included",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bandwidth Units Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(avalanche_${CHAIN_ID}_vm_hypersdk_chain_units_executed_bandwidth[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Block Execution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Compute Units Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(avalanche_${CHAIN_ID}_vm_hypersdk_chain_units_executed_compute[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Block Execution Backlog",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avalanche_${CHAIN_ID}_vm_hypersdk_chain_engine_backlog",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wait Auth",
   "type": "timeseries",
   "description": "Subset of Block Execution",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Wait Repeat",
   "type": "timeseries",
   "description": "Subset of Block Execution",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Wait Queue",
   "type": "timeseries",
   "description": "Subset of Block Execution",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Wait Precheck",
   "type": "timeseries",
   "description": "Subset of Block Execution",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Wait Executor",
   "type": "timeseries",
   "description": "Subset of Block Execution",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Wait Commit",
   "type": "timeseries",
   "description": "Subset of Block Execution",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Executable Transactions (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A/($A+$B)", "type": "math" }
   ]
  },
  {
   "title": "Invalid Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "targets": [
    {
     "expr": "rate(avalanche_${CHAIN_ID}_vm_hypersdk_vm_txs_invalid[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Executed Epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "targets": [
    {
     "expr": "avalanche_${CHAIN_ID}_vm_hypersdk_chain_last_executed_epoch",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "State Management", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Allocate Units Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "rate(avalanche_${CHAIN_ID}_vm_hypersdk_chain_units_executed_allocate[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Units Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 43 },
   "targets": [
    {
     "expr": "rate(avalanche_${CHAIN_ID}_vm_hypersdk_chain_units_executed_write[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read Units Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "rate(avalanche_${CHAIN_ID}_vm_hypersdk_chain_units_executed_read[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State Changes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 43 },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Wait Batch Initialization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Batches Rewritten",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(avalanche_${CHAIN_ID}_vm_hypersdk_vilmo_batches_rewritten[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch Initialization Writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Wait Batch Prepare",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Wait TState Iterate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Wait Batch Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "State Keys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avalanche_${CHAIN_ID}_vm_hypersdk_vilmo_keys",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alive Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avalanche_${CHAIN_ID}_vm_hypersdk_vilmo_alive_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Useless Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avalanche_${CHAIN_ID}_vm_hypersdk_vilmo_useless_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Consensus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Blocks Processing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "avalanche_${CHAIN_ID}_blks_processing",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks Accepted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 76 },
   "targets": [
    {
     "expr": "rate(avalanche_${CHAIN_ID}_blks_accepted_count[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks Rejected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 76 },
   "targets": [
    {
     "expr": "rate(avalanche_${CHAIN_ID}_blks_rejected_count[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network (Chits)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(avalanche_${CHAIN_ID}_handler_chits_sum[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network (Push Query)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(avalanche_${CHAIN_ID}_handler_push_query_sum[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network (Notify)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(avalanche_${CHAIN_ID}_handler_notify_sum[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network (Put)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(avalanche_${CHAIN_ID}_handler_put_sum[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network (Get)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(avalanche_${CHAIN_ID}_handler_get_sum[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network (Pull Query)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(avalanche_${CHAIN_ID}_handler_pull_query_sum[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Virtual Machine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Network Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avalanche_requests_average_latency",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unprocessed Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avalanche_${CHAIN_ID}_handler_unprocessed_msgs_len",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unprocessed Async Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avalanche_${CHAIN_ID}_handler_async_unprocessed_msgs_len",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App Request (Sent)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(avalanche_network_app_request_sent[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App Request (Received)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(avalanche_network_app_request_received[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App Gossip (Sent)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(avalanche_network_app_gossip_sent[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App Gossip (Received)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(avalanche_network_app_gossip_received[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Built Chunks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "targets": [
    {
     "expr": "rate(avalanche_${CHAIN_ID}_vm_hypersdk_chain_chunk_build_count[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Collect Chunk Signatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Dropped Chunks (Gossip)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(avalanche_${CHAIN_ID}_vm_hypersdk_chain_chunk_gossip_dropped[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chunk Backlog (Gossip)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avalanche_${CHAIN_ID}_vm_hypersdk_chain_gossip_chunk_backlog",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Expired Built Chunks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(avalanche_${CHAIN_ID}_vm_hypersdk_chain_expired_built_chunks[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fetch Chunk Attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 133 },
   "targets": [
    {
     "expr": "increase(avalanche_${CHAIN_ID}_vm_hypersdk_chain_fetch_chunk_attempts[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Useless Fetch Chunk Attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 133 },
   "targets": [
    {
     "expr": "increase(avalanche_${CHAIN_ID}_vm_hypersdk_chain_useless_fetch_chunk_attempts[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Optimistic Chunk Certificates Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 133 },
   "targets": [
    {
     "expr": "increase(avalanche_${CHAIN_ID}_vm_hypersdk_chain_optimistic_certified_gossip[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get Chunks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Transaction Backlog (RPC)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avalanche_${CHAIN_ID}_vm_hypersdk_chain_rpc_tx_backlog",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Backlog (Gossip)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avalanche_${CHAIN_ID}_vm_hypersdk_chain_gossip_tx_backlog",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dropped Transactions (Gossip)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 141 },
   "targets": [
    {
     "expr": "rate(avalanche_${CHAIN_ID}_vm_hypersdk_chain_tx_gossip_dropped[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Expiry Remaining When Added to Mempool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 149 },
   "targets": [
    {
     "expr": "avalanche_${CHAIN_ID}_vm_hypersdk_chain_mempool_len",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining Txs in Mempool After Build",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 149 },
   "targets": [
    {
     "expr": "rate(avalanche_${CHAIN_ID}_vm_hypersdk_chain_remaining_mempool[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invalid Gossip (TxMsg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(avalanche_${CHAIN_ID}_vm_hypersdk_chain_gossip_tx_msg_invalid[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invalid Gossip (Tx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(avalanche_${CHAIN_ID}_vm_hypersdk_chain_gossip_tx_invalid[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invalid Gossip (Chunk)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(avalanche_${CHAIN_ID}_vm_hypersdk_chain_gossip_chunk_invalid[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invalid Gossip (Chunk Signature)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 165 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(avalanche_${CHAIN_ID}_vm_hypersdk_chain_gossip_chunk_sig_invalid[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invalid Transaction (RPC)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 165 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(avalanche_${CHAIN_ID}_vm_hypersdk_chain_rpc_tx_invalid[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chain Data Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 165 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avalanche_${CHAIN_ID}_vm_hypersdk_chain_data_size",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deleted Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 173 },
   "targets": [
    {
     "expr": "rate(avalanche_${CHAIN_ID}_vm_hypersdk_vm_deleted_blocks[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deleted Chunks (Included)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 173 },
   "targets": [
    {
     "expr": "rate(avalanche_${CHAIN_ID}_vm_hypersdk_vm_deleted_included_chunks[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deleted Chunks (Useless)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 173 },
   "targets": [
    {
     "expr": "rate(avalanche_${CHAIN_ID}_vm_hypersdk_vm_deleted_useless_chunks[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 181 } },
  {
   "title": "Memory Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (node_memory_MemTotal_bytes{job=~\"avalanchego-machine\"} - node_memory_MemFree_bytes{job=~\"avalanchego-machine\"} - node_memory_Buffers_bytes{job=~\"avalanchego-machine\"} - node_memory_Cached_bytes{job=~\"avalanchego-machine\"}) / node_memory_MemTotal_bytes{job=~\"avalanchego-machine\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{job=~\"avalanchego-machine\", mode=\"idle\"}[30s])) by (instance)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "avalanche_go_goroutines", "legendFormat": "avalanchego: {{instance}}" },
    {
     "expr": "avalanche_${CHAIN_ID}_vm_go_goroutines",
     "legendFormat": "nuklaivm: {{instance}}"
    }
   ]
  },
  {
   "title": "CPU Idle Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode=\"idle\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network I/O (Sent)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"ens5\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Packets (Sent)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_packets_total{device=\"ens5\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network I/O (Received)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"ens5\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Packets (Received)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total{device=\"ens5\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Bandwidth (Write/Second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 198 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Bandwidth (Write/Minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 198 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(node_disk_written_bytes_total[60s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Ops (Write)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 198 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed_total[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 198 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expression": "$B/$A", "type": "math" }
   ]
  },
  {
   "title": "Disk Bandwidth (Read/Second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 206 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Bandwidth (Read/Minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 206 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(node_disk_read_bytes_total[60s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Ops (Read)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 206 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 206 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expression": "$B/$A", "type": "math" }
   ]
  },
  {
   "title": "Disk I/O Now",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "node_disk_io_now", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk I/O Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU I/O Wait",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode=\"iowait\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Rate Limiting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 222 } },
  {
   "title": "Unprocessed Messages (Excessive CPU)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 223 },
   "targets": [
    {
     "expr": "rate(avalanche_${CHAIN_ID}_handler_unprocessed_msgs_excessive_cpu[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Async Unprocessed Messages (Excessive CPU)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 223 },
   "targets": [
    {
     "expr": "rate(avalanche_${CHAIN_ID}_handler_async_unprocessed_msgs_excessive_cpu[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Throttler (Outbound Acquire Failures)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 223 },
   "targets": [
    {
     "expr": "rate(avalanche_network_throttler_outbound_acquire_failures[30s])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}