# Copyright (C) 2023, AllianceBlock. All rights reserved.
# See the file LICENSE for licensing terms.

name: NuklaiVM CI
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  go-mod-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: ./.github/actions/install-go
      - shell: bash
        run: go mod tidy
      - shell: bash
        working-directory: ./
        run: go mod tidy
      - shell: bash
        run: scripts/tests.clean.sh

  nuklaivm-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: ./.github/actions/install-go
        with:
          cache-dependency-path: |
            go.sum
      - name: Run static analysis tests
        shell: bash
        run: scripts/tests.lint.sh
      - name: Build vm, cli, faucet, feed
        shell: bash
        run: scripts/build.sh

  nuklaivm-unit-tests:
    runs-on: ubuntu-20.04-32
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: ./.github/actions/install-go
        with:
          cache-dependency-path: |
            go.sum
      - name: Run unit tests
        shell: bash
        run: scripts/tests.unit.sh
      - name: Run integration tests
        shell: bash
        run: scripts/tests.integration.sh
      # - name: Archive code coverage results (text)
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: code-coverage-out
      #     path: ./integration.coverage.out
      # - name: Archive code coverage results (html)
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: code-coverage-html
      #     path: ./integration.coverage.html
      - name: Run e2e tests
        shell: bash
        run: scripts/run.sh
        env:
          MODE: 'test'

  nuklaivm-tests:
    runs-on: ubuntu-latest
    needs: [go-mod-tidy, nuklaivm-lint, nuklaivm-unit-tests]
    steps:
      - name: Finished NuklaiVM tests
        run: echo "Finished NuklaiVM tests"

  nuklaivm-load-tests:
    needs: [nuklaivm-unit-tests]
    strategy:
      matrix:
        level: [v1, v2, v3] # v4 is not supported
    runs-on: ubuntu-20.04-32
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: ./.github/actions/install-go
        with:
          cache-dependency-path: |
            go.sum
      - name: Run load tests
        shell: bash
        run: GOAMD64=${{ matrix.level }} scripts/tests.load.sh

  nuklaivm-sync-tests:
    needs: [nuklaivm-unit-tests]
    runs-on: ubuntu-20.04-32
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: ./.github/actions/install-go
        with:
          cache-dependency-path: |
            go.sum
      - name: Run sync tests
        shell: bash
        run: scripts/run.sh
        env:
          MODE: 'full-test'

  nuklaivm-release:
    needs: [nuklaivm-load-tests, nuklaivm-sync-tests]
    # We build with 20.04 to maintain max compatibility: https://github.com/golang/go/issues/57328
    runs-on: ubuntu-20.04-32
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/vm-release
        with:
          vm-name: nuklaivm
          github-token: ${{ secrets.GITHUB_TOKEN }}
