# Copyright (C) 2023, AllianceBlock. All rights reserved.
# See the file LICENSE for licensing terms.

name: NuklaiVM Sync Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [labeled, synchronize, reopened]

jobs:
  nuklaivm-sync-tests:
    if: ${{ github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'run sync') }}
    # runs-on: dev
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true
          cache: true
          cache-dependency-path: |
            go.sum
      - name: Run sync tests
        working-directory: ./
        shell: bash
        run: mkdir -p /data/github/tmp/nuklaivm && scripts/run.sh /data/github/tmp/nuklaivm
        env:
          MODE: 'full-test'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
